### ISSUE TITLE
End screen AND questionnaire needs to be implemented properly to prevent clashes with other features

### ISSUE THREAD

**Issue by Nivrad00** [Nivrad00/social-landmines#18]
It should probably be under Screens or something, instead of stuck into Main.tscn. Also need to make sure it doesn't clash with rollback, save/load, and the in-game menu.

**Comment by Nivrad00** [comment]
additional note: questionnaire is on separate rakugo scene, that might cause issues with rollback

**Comment by rawreon** [comment]
questionnaire works with save/load, roll back rolls back to the questionnaire(this should not happen), need to somehow limit to one rakugo scene
