### ISSUE TITLE
Various end screen issues

### ISSUE THREAD

**Issue by Nivrad00** [Nivrad00/social-landmines#35]
1. Text can overflow off top/bottom of screen if there's too many supports/stressors
2. The "supports" variables didn't seem to be saved correctly in Global, and thus didn't display on the end screen. I'm too tired to figure out why right now, but it's worth checking to see if a) they're being set correctly in the first place, and b) they're being saved correctly after saving/loading
3. There's a weird empty space if the player had no supports or no stressors
4. Once again, the game breaks when using rollback or save/load on this screen. This bug has been known and has a separate issue opened.

**Comment by ben-rampel** [comment]
2 fixed

**Comment by Nivrad00** [comment]
4 fixed :)

**Comment by rawreon** [comment]
adding scroll container should fix 1, have not tested extensively
