### ISSUE TITLE
Questionnaire variables/mood not correctly retrieved when rolling back or loading

### ISSUE THREAD

**Issue by Nivrad00** [Nivrad00/social-landmines#38]
Rakugo doesn't remember the questionnaire variables when it "jumps," which breaks both rollback and load.
Also, I had a glitch where every time you rollback, the themometer would go higher and higher. This might mean the thermometer isn't being reset to its initial value when Rakugo "jumps"

**Comment by ben-rampel** [comment]
global variables now saved with rakugo
